// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mrfwsucpbiacbpowhhxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1yZndzdWNwYmlhY2Jwb3doaHhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMTA5MzYsImV4cCI6MjA2OTY4NjkzNn0.BsPPTpGrTGKeFQKwU24EbzXsNKFgzAcjrf8z70H75Tw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});